[model]
provider = "gradient_ai"
name = "llama3.3-70b-instruct"
temperature = 0
max_tokens = 1500

[prompt]
persona = "You are an assistant of an ecology researcher that is conducting the initial screening of studies for a meta-analysis.\n"
instruction = "Recommend inclusion or not of a scientific study and explain your decision.\n"
context = "You will be given criteria for inclusion. The user will give you the study's title and abstract.\n"

data_format = """
Create a valid JSON output. Follow this schema:
{
    "verdict": "{1 inclusion, 0 not}",
    "reason": "{short explanation supporting the decision}"
}
"""

[criteria]
text = """
Include only studies that test how good are LLMs compared to humans for screening papers.
"""
